### ISSUE TITLE
Changes to view

### ISSUE THREAD

**Issue by coding-sunshine** [themsaid/laravel-langman-gui#1]
Thanks for the great package. :) 
Is there anyways I can make changes to the views? as I want to give facility to update languages to my team, so i want to make it feel as part of my own app.

**Comment by themsaid** [comment]
But this package is meant to be used by developers so far, since you'll need to commit the changes made by the package to your source control.

**Comment by coding-sunshine** [comment]
Ok got your Idea. I will try to build something upon this. As basically my idea was, we have to make the site accessible in Swedish, apart from english, but none of our developers know the language. And the client offered if he gets the list of strings he can translate them for us in excel sheet. But then I thought if we had an option to update UI then I can somehow integrate the code to admin panel from where client can change and save the files and later on we can commit it. 
Thanks for the package though again, saved me a lot of time already :)
