### ISSUE TITLE
Redesign with two vertical sections

### ISSUE THREAD

**Issue by meness** [themsaid/laravel-langman-gui#12]
Hi,

You put strings into a fixed-width box. I think it's better to split the page into two vertical sections. the left one totally has strings and it fills whole its space and the other one is used to change strings as it is now.

**Comment by themsaid** [comment]
Can you share a wireframe for what you propose?

**Comment by AdrianKuriata** [comment]
I think he mean

```
<div class="row">
<div class="col-xs-12 col-sm-6">
Box with strings
</div>

<div class="col-xs-12 col-sm-6">
Box with do translation
</div>
</div>
```

**Comment by themsaid** [comment]
no plans for this, sorry :)
