### ISSUE TITLE
Highlight strings with missing placeholders and/or wrong placeholders

### ISSUE THREAD

**Issue by meness** [themsaid/laravel-langman-gui#13]

**Comment by themsaid** [comment]
More details on that please.

**Comment by meness** [comment]
@themsaid Sure!

Laravel uses a colon (`:`) as a placeholder in translations (i.e. `__('Hello :name', ['name'=>'Alireza'])`). It's good to see those placeholders highlighted.

**Comment by themsaid** [comment]
no plans for this, sorry :)
