### ISSUE TITLE
Make the save and sync ajax call relative

### ISSUE THREAD

**Issue by pagongski** [themsaid/laravel-langman-gui#15]
My langman install wasnt saving the new keys and updates, but after some digging i found its because of the ajax call to "/langman/save". Since i dont run my project on the top level, this call fails. Editing it to "langman/save" solves the problem.

Would it be possible to fix it? Or is there a way that i can do it? :-)

Also, thank you for the great package. Helps me save some serious time with the translation woes.

**Comment by danijelk** [comment]
I think it should either be changed to "save" or $request->path().'/save'

**Comment by pagongski** [comment]
Maybe"langman" should stay on the path to distinguish it from some generic service/path/route.

**Comment by pagongski** [comment]
To make a pull request, i have to create a fork and make the changes there?

**Comment by themsaid** [comment]
Feel free to open a PR :)
