### ISSUE TITLE
trans_choice not picked up

### ISSUE THREAD

**Issue by tfortier** [themsaid/laravel-langman-gui#16]
Hi,

Great package, thanks for that!

One tiny little hiccup for me is I was using {{ trans('Some string') }} and those didn't get picked up by the scan. I changed them all to __('') which were scanned properly.

That does leave me with quite a few {{ trans_choice(...) }} that are not getting scanned.

Do you plan on supporting those at some point?

**Comment by danijelk** [comment]
It's in my pull request, which will probably be merged within the next 24h if the author doesn't have any more comments, this will enable you to add your functions that your project uses instead of the static '__'

**Comment by themsaid** [comment]
`trans()` and `trans_choice()` can be used for array translations as well, that's why we don't scan for them by default, however you can add a `localization_methods` config key which is available since `0.1.2`.

```
'localization_methods' => ['__', 'trans', 'trans_choice'],
```

**Comment by tfortier** [comment]
After running `composer update` and fetching the new version, the translation tool seems utterly confused so I must be missing something.

I emptied my en.json and fr.json files and made a scan. Instead of the 100+ items it found previously I now have only three results : `__`, `trans` and `trans_choice`.

My config file looks like this : 

```
<?php

return [
    'base_language' => 'fr',
    'localization_methods' => ['__', 'trans', 'trans_choice'],
    'route_group_config' => [
        'middleware' => ['web'],
        'namespace' => 'Themsaid\LangmanGUI'
    ]
];
```

**Comment by themsaid** [comment]
@tfortier I just released a new fix on v0.1.3, give it a try.

**Comment by tfortier** [comment]
Works like a charm. Thank you very much 👍

**Comment by themsaid** [comment]
Welcome :)
