### ISSUE TITLE
"0 Keys" error

### ISSUE THREAD

**Issue by marioene** [themsaid/laravel-langman-gui#18]
Hi,

After installing the component in a new Laravel project and publishing the config, I have this error in browser:

Top menu:
`Laravel Langman 0 Keys`

Content:
`There are no JSON translation keys in your project, start by creating json
files for every language in your "resources/lang" directory.
In case you have the files already created, you may now start adding keys or
let Langman scan your project for lines to translate. `

Environment:
OS: Windows 10 Pro
Laragon 2.2.2 (Apache 2.4.25, PHP 7.1.1)

**Comment by themsaid** [comment]
The error is explaining the issue, you need to add json translation files to your project!

**Comment by marioene** [comment]
Of course I have in folders: 'resources/lang/en' and 'resources/lang/ro' default files for translations (from Laravel 5.4) in English and Romanian languages. Your component langman is working fine, like command `php artisan langman:show auth`, for example.

**Comment by themsaid** [comment]
This package only works for JSON translation files at the moment, those files should be placed in `resources/lang` as in `resources/lang/en.json` for example.
