### ISSUE TITLE
Don't use default scrollbar, use a modern one

### ISSUE THREAD

**Issue by meness** [themsaid/laravel-langman-gui#22]
Hi,

There're lots of modern scrollbars out there, please use one of them (specially auto-hide scrollbars) instead of default scrollbar.

**Comment by themsaid** [comment]
why?

**Comment by meness** [comment]
@themsaid Really? Because they have a more beautiful interface, they also provide an auto-hide option. They're better than the default scrollbar.

**Comment by themsaid** [comment]
No plans for this at the moment, sorry :)
