### ISSUE TITLE
Bugged creating language and scaning for new lang file

### ISSUE THREAD

**Issue by AdrianKuriata** [themsaid/laravel-langman-gui#24]
Hi, maybe i did something wrong but when i go to /langman route i see i dont have JSON lang files and i can create it, after that into selecting language [LINK](http://i.imgur.com/kAusQ6R.png) i have double lang file name. When i try scan files i getting information about langman found new keys but this is not added for this lang. If i add something to en.json file manually and scan it, everything working perfect, but when i create new lang file manually(i can't create new file from langman GUI) i getting internal 500 error into browser console. If i add to new created file json array `{}` item is scan, but is not added to my new language.

If you can let me know step by step how can i add new translations and how i should work with langman.

//Edit: I fixed something from this buggs, tommorow i will add PR with this and maybe some improvments :D

**Comment by themsaid** [comment]
this is fixed now, thanks :)
