### ISSUE TITLE
Scan doesn't work on fresh project and install

### ISSUE THREAD

**Issue by slakbal** [themsaid/laravel-langman-gui#27]
Hi Mohammed,

I have a fresh install of everything and a single view with the following:

__("This is a test")

Clicking on the scan I can see that the endpoint does return the correct value:

["This is a test"]

but the Vue component throws the following error:

`
langman.js:42763 Uncaught TypeError: Cannot read property 'This is a test' of undefined
    at Vue$3.addNewKey (langman.js:42763)
    at Vue$3.boundFn [as addNewKey] (langman.js:33189)
    at _.forEach.key (langman.js:42835)
    at arrayEach (langman.js:14459)
    at Function.forEach (langman.js:23281)
    at Object.$.post.done.response (langman.js:42834)
    at fire (langman.js:6979)
    at Object.fireWith [as resolveWith] (langman.js:7109)
    at done (langman.js:12934)
    at XMLHttpRequest.<anonymous> (langman.js:13176)
`

Are you getting it also on a fresh install?

**Comment by stefro** [comment]
I have this same issue.

**Comment by seschi98** [comment]
Me too.

**Comment by robsontenorio** [comment]
I think the problem is "cache files" from langman. Just delete all files in "storage/langmanGUI"

**Comment by seschi98** [comment]
Did that already, problem still present...
When I click on "Scan" it just creates a new folder with an en.json in it. The file contains only an empty JSON Object.

**Comment by robsontenorio** [comment]
1) clear cached files (storage/langmanGUI)
2) clear json files (en.json , fr.json ...)
3) open web interface with an  anonymous session in Chrome 
4) add a language file (ex "fr")
5) scan

**Comment by seschi98** [comment]
Still not working 😏

**Comment by tutNichts** [comment]
@themsaid some news here? I really want to use it! Would be great if it works! :-)

**Comment by bivinvinod** [comment]
Same here...

**Comment by coldKingdom** [comment]
I renamed the "en" folder in resources/lang to something else, cleared all the caches and started over again , seemed to be working for me :)

**Comment by themsaid** [comment]
This is fixed now. thanks everyone.

**Comment by ali-syria** [comment]
still not working

**Comment by stefro** [comment]
I had the same issue. I noticed that there was no json file for the base language in the `resources/lang` dir. 
After creating an `en.json` file with only `{}` in the file everything worked as expected.
