### ISSUE TITLE
installed the package interface css and js not loading properly

### ISSUE THREAD

**Issue by ramisohail** [themsaid/laravel-langman-gui#29]
i just installed the packaged put the service provider published the files and went to www.myapp.com/langman

![image](https://cloud.githubusercontent.com/assets/24530983/26757191/79410844-48bd-11e7-99cc-8658b500fda3.png)

what is the issue, please help?

**Comment by coldKingdom** [comment]
I don't know the issue really. But using:

`php artisan vendor:publish --provider="Themsaid\LangmanGUI\LangmanServiceProvider"`

Instead of:

`php artisan vendor:publish --provider=Themsaid\\LangmanGUI\\LangmanServiceProvider`

Worked for me :)
