### ISSUE TITLE
It cannot find my languages

### ISSUE THREAD

**Issue by meness** [themsaid/laravel-langman-gui#5]
Hi,

My base language is `fa`, and the English lang path is `/resources/lang/en/` but the tool continually says:

> There are no JSON translation keys in your project, start by creating JSON 
> files for every language in your "resources/lang" directory.
> 
> In case you have the files already created, you may now start adding keys or 
> let Langman scan your project for lines to translate.

**Comment by SkifAlef** [comment]
You have to create fa.json and en.json directly in /resources/lang directiory, not in /resources/lang/en and /fa subdirectories

**Comment by meNESS** [comment]
@SkifAlef Well, it works now, but isn't that illegal? You mean I have to put any strings in just one JSON file instead of multiple files?

**Comment by SkifAlef** [comment]
Well, this is the idea of json-based localization as I see it. When number of strings to localize grows over some margin it's actually more convenient to stop structure them at all, 'cause overhead for maintaing it is too much.

Anyway, you can still totally use classic non-json method with /lang/locale/file.php files.

**Comment by meness** [comment]
@SkifAlef You're right about the new JSON-based localization way. What about already provided strings with Laravel (e.g. `validation.php`)? Should I also put them inside JSON files?

**Comment by SkifAlef** [comment]
Well, it's totally up yo you, there's no some _proper_ way to do it.
I'd leave 'em as they be, 'cause usually you just one time localize those strings and forget about 'em

**Comment by meness** [comment]
@SkifAlef Thanks for the help ❤️
